#Name action to Pytest
name: Pytest

#State when action should run, in our case on every push
on: [push]

#Create a job section where we will define steps to be run for our Pytest
jobs:

  #Call build to execute the different steps for our Pytest
  build:

    #Define operating system on which to run tests
    runs-on: ubuntu-latest

    #Define strategies to run our test on different python versions
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    #Create a step section with the steps to run the Pytest
    steps:
      - 


  
